"""
Generate training dataset for function calling model.
Creates 50 examples per function (9 functions = 450 total).
"""
import json
import random

# Tool definitions (shared across all examples)
TOOLS = [
    {"type": "function", "function": {"name": "control_light", "description": "Control smart lights - turn on, off, dim, or change color", "parameters": {"type": "object", "properties": {"action": {"type": "string"}, "device_name": {"type": "string"}, "brightness": {"type": "integer"}, "color": {"type": "string"}}, "required": ["action"]}}},
    {"type": "function", "function": {"name": "set_timer", "description": "Set a countdown timer", "parameters": {"type": "object", "properties": {"duration": {"type": "string"}, "label": {"type": "string"}}, "required": ["duration"]}}},
    {"type": "function", "function": {"name": "set_alarm", "description": "Set an alarm for a specific time", "parameters": {"type": "object", "properties": {"time": {"type": "string"}, "label": {"type": "string"}}, "required": ["time"]}}},
    {"type": "function", "function": {"name": "create_calendar_event", "description": "Create a calendar event", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "date": {"type": "string"}, "time": {"type": "string"}, "duration": {"type": "integer"}}, "required": ["title"]}}},
    {"type": "function", "function": {"name": "add_task", "description": "Add a task to the to-do list", "parameters": {"type": "object", "properties": {"text": {"type": "string"}, "priority": {"type": "string"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "web_search", "description": "Search the web for information", "parameters": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}}},
    {"type": "function", "function": {"name": "get_system_info", "description": "Get current system state including timers, calendar, tasks, devices, and weather", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "thinking", "description": "Use for complex queries requiring reasoning, math, coding, or multi-step analysis", "parameters": {"type": "object", "properties": {"prompt": {"type": "string"}}, "required": ["prompt"]}}},
    {"type": "function", "function": {"name": "nonthinking", "description": "Use for simple queries, greetings, factual questions not requiring deep reasoning", "parameters": {"type": "object", "properties": {"prompt": {"type": "string"}}, "required": ["prompt"]}}}
]

SYSTEM_MSG = "You are a model that can do function calling with the following functions"

def make_example(user_content, func_name, args):
    return {
        "messages": [
            {"role": "developer", "content": SYSTEM_MSG},
            {"role": "user", "content": user_content},
            {"role": "assistant", "tool_calls": [{"type": "function", "function": {"name": func_name, "arguments": args}}]}
        ],
        "tools": TOOLS
    }

# ============ CONTROL_LIGHT (50 examples) ============
control_light_examples = [
    ("Turn on the living room lights", {"action": "on", "device_name": "living room"}),
    ("Turn off the bedroom light", {"action": "off", "device_name": "bedroom"}),
    ("Dim the kitchen lights to 50%", {"action": "dim", "device_name": "kitchen", "brightness": 50}),
    ("Switch on all the lights", {"action": "on", "device_name": "all"}),
    ("Make the office light blue", {"action": "on", "device_name": "office", "color": "blue"}),
    ("Set the bathroom light to 25%", {"action": "dim", "device_name": "bathroom", "brightness": 25}),
    ("Toggle the hallway lights", {"action": "toggle", "device_name": "hallway"}),
    ("Lights off everywhere", {"action": "off", "device_name": "all"}),
    ("Change the living room to warm white", {"action": "on", "device_name": "living room", "color": "warm white"}),
    ("Set brightness to full in the garage", {"action": "dim", "device_name": "garage", "brightness": 100}),
    ("Turn the porch light on", {"action": "on", "device_name": "porch"}),
    ("Kill the lights in the den", {"action": "off", "device_name": "den"}),
    ("Brighten the dining room", {"action": "dim", "device_name": "dining room", "brightness": 100}),
    ("Set bedroom to red", {"action": "on", "device_name": "bedroom", "color": "red"}),
    ("Lower the office lights to 30", {"action": "dim", "device_name": "office", "brightness": 30}),
    ("Lights on in basement", {"action": "on", "device_name": "basement"}),
    ("Switch off kitchen light", {"action": "off", "device_name": "kitchen"}),
    ("Make it brighter in here", {"action": "dim", "device_name": "current room", "brightness": 80}),
    ("Dim all lights to 40%", {"action": "dim", "device_name": "all", "brightness": 40}),
    ("Set the nursery to soft pink", {"action": "on", "device_name": "nursery", "color": "pink"}),
    ("Turn on lamp", {"action": "on", "device_name": "lamp"}),
    ("Shut off the desk light", {"action": "off", "device_name": "desk"}),
    ("Bedroom lights at half", {"action": "dim", "device_name": "bedroom", "brightness": 50}),
    ("Change color to green in kids room", {"action": "on", "device_name": "kids room", "color": "green"}),
    ("Maximize brightness in study", {"action": "dim", "device_name": "study", "brightness": 100}),
    ("Turn off outside lights", {"action": "off", "device_name": "outside"}),
    ("Switch the attic light on", {"action": "on", "device_name": "attic"}),
    ("Dim patio lights", {"action": "dim", "device_name": "patio", "brightness": 40}),
    ("Set all lights to cool white", {"action": "on", "device_name": "all", "color": "cool white"}),
    ("Make the closet light brighter", {"action": "dim", "device_name": "closet", "brightness": 75}),
    ("Lights to 10% in master bedroom", {"action": "dim", "device_name": "master bedroom", "brightness": 10}),
    ("Turn on reading lamp", {"action": "on", "device_name": "reading lamp"}),
    ("Office to daylight mode", {"action": "on", "device_name": "office", "color": "daylight"}),
    ("Kill all the lights", {"action": "off", "device_name": "all"}),
    ("Set movie mode lighting", {"action": "dim", "device_name": "living room", "brightness": 20}),
    ("Bathroom at full brightness", {"action": "dim", "device_name": "bathroom", "brightness": 100}),
    ("Purple light in gaming room", {"action": "on", "device_name": "gaming room", "color": "purple"}),
    ("Lower all lights", {"action": "dim", "device_name": "all", "brightness": 30}),
    ("Switch on the ceiling fan light", {"action": "on", "device_name": "ceiling fan"}),
    ("Turn off stairway lights", {"action": "off", "device_name": "stairway"}),
    ("Entryway light on", {"action": "on", "device_name": "entryway"}),
    ("Dim the table lamp to 60", {"action": "dim", "device_name": "table lamp", "brightness": 60}),
    ("Set accent lights to orange", {"action": "on", "device_name": "accent", "color": "orange"}),
    ("Guest room lights off", {"action": "off", "device_name": "guest room"}),
    ("Brighten up the workspace", {"action": "dim", "device_name": "workspace", "brightness": 90}),
    ("Night light on", {"action": "on", "device_name": "night light"}),
    ("Set laundry room to 50%", {"action": "dim", "device_name": "laundry room", "brightness": 50}),
    ("Yellow lights in sunroom", {"action": "on", "device_name": "sunroom", "color": "yellow"}),
    ("Mudroom light off", {"action": "off", "device_name": "mudroom"}),
    ("Front porch to warm", {"action": "on", "device_name": "front porch", "color": "warm"}),
    ("Turn on the chandelier", {"action": "on", "device_name": "chandelier"}),
    ("Kill the basement lights", {"action": "off", "device_name": "basement"}),
    ("Set reading light to 40%", {"action": "dim", "device_name": "reading light", "brightness": 40}),
    ("Change bedroom to cool white", {"action": "on", "device_name": "bedroom", "color": "cool white"}),
    ("Lights up in the hallway", {"action": "dim", "device_name": "hallway", "brightness": 100}),
    ("Turn off the aquarium light", {"action": "off", "device_name": "aquarium"}),
    ("Set deck lights to amber", {"action": "on", "device_name": "deck", "color": "amber"}),
    ("Dim living room to 10%", {"action": "dim", "device_name": "living room", "brightness": 10}),
    ("Switch on the garage light", {"action": "on", "device_name": "garage"}),
    ("Make the kitchen light blue", {"action": "on", "device_name": "kitchen", "color": "blue"}),
    ("Turn off all upstairs lights", {"action": "off", "device_name": "upstairs"}),
    ("Set master bath to daylight", {"action": "on", "device_name": "master bath", "color": "daylight"}),
    ("Brighten the vanity mirror", {"action": "dim", "device_name": "vanity mirror", "brightness": 85}),
    ("Turn on the floodlights", {"action": "on", "device_name": "floodlights"}),
    ("Lower the dining light to 25", {"action": "dim", "device_name": "dining room", "brightness": 25}),
    ("Set strip lights to purple", {"action": "on", "device_name": "strip lights", "color": "purple"}),
    ("Lights out in the guest room", {"action": "off", "device_name": "guest room"}),
    ("Turn on the pantry light", {"action": "on", "device_name": "pantry"}),
    ("Set bedside lamp to warm", {"action": "on", "device_name": "bedside lamp", "color": "warm"}),
    ("Dim the foyer lights", {"action": "dim", "device_name": "foyer", "brightness": 50}),
    ("Switch off the attic", {"action": "off", "device_name": "attic"}),
    ("Make the gym light red", {"action": "on", "device_name": "gym", "color": "red"}),
    ("Set nursery light to 5%", {"action": "dim", "device_name": "nursery", "brightness": 5}),
    ("Turn on the closet light", {"action": "on", "device_name": "closet"}),
    ("Lights off in the study", {"action": "off", "device_name": "study"}),
    ("Set patio to soft white", {"action": "on", "device_name": "patio", "color": "soft white"}),
    ("Increase brightness in kitchen", {"action": "dim", "device_name": "kitchen", "brightness": 90}),
    ("Turn off the nightstand light", {"action": "off", "device_name": "nightstand"}),
    ("Set under cabinet lights to green", {"action": "on", "device_name": "under cabinet", "color": "green"}),
    ("Turn on the shed light", {"action": "on", "device_name": "shed"}),
    ("Dim the movie room to zero", {"action": "off", "device_name": "movie room"}),
    ("Set hallway to 20 percent", {"action": "dim", "device_name": "hallway", "brightness": 20}),
    ("Change living room to candle light", {"action": "on", "device_name": "living room", "color": "candle light"}),
    ("Switch on the desk lamp", {"action": "on", "device_name": "desk lamp"}),
    ("Turn off the laundry light", {"action": "off", "device_name": "laundry"}),
    ("Set balcony lights to yellow", {"action": "on", "device_name": "balcony", "color": "yellow"}),
    ("Brighten the garage", {"action": "dim", "device_name": "garage", "brightness": 100}),
    ("Turn on the floor lamp", {"action": "on", "device_name": "floor lamp"}),
    ("Set toilet light to blue", {"action": "on", "device_name": "toilet", "color": "blue"}),
    ("Dim the art light", {"action": "dim", "device_name": "art light", "brightness": 60}),
    ("Lights out in the library", {"action": "off", "device_name": "library"}),
    ("Turn on the monitor backlights", {"action": "on", "device_name": "monitor backlights"}),
    ("Set garden lights to white", {"action": "on", "device_name": "garden", "color": "white"}),
    ("Lower the bedroom lights", {"action": "dim", "device_name": "bedroom", "brightness": 40}),
    ("Switch off the workbench", {"action": "off", "device_name": "workbench"}),
    ("Make the entryway bright", {"action": "dim", "device_name": "entryway", "brightness": 100}),
    ("Turn on the lava lamp", {"action": "on", "device_name": "lava lamp"}),
    ("Set ceiling lights to 75%", {"action": "dim", "device_name": "ceiling", "brightness": 75}),
    ("Change bathroom to magenta", {"action": "on", "device_name": "bathroom", "color": "magenta"}),
    ("Turn off the showcase light", {"action": "off", "device_name": "showcase"}),
]

# ============ SET_TIMER (50 examples) ============
set_timer_examples = [
    ("Set a timer for 10 minutes", {"duration": "10 minutes"}),
    ("Timer for 5 mins", {"duration": "5 minutes"}),
    ("Set a 30 second timer", {"duration": "30 seconds"}),
    ("Start a one hour timer", {"duration": "1 hour"}),
    ("Timer 15 minutes for eggs", {"duration": "15 minutes", "label": "eggs"}),
    ("Set pasta timer 8 minutes", {"duration": "8 minutes", "label": "pasta"}),
    ("Create a timer for 45 minutes", {"duration": "45 minutes"}),
    ("Set a 2 minute timer", {"duration": "2 minutes"}),
    ("Timer for laundry 1 hour", {"duration": "1 hour", "label": "laundry"}),
    ("Start 20 minute workout timer", {"duration": "20 minutes", "label": "workout"}),
    ("Set timer 3 minutes", {"duration": "3 minutes"}),
    ("Pizza timer 12 minutes", {"duration": "12 minutes", "label": "pizza"}),
    ("Timer for 25 minutes pomodoro", {"duration": "25 minutes", "label": "pomodoro"}),
    ("Set a quick 1 minute timer", {"duration": "1 minute"}),
    ("90 second timer please", {"duration": "90 seconds"}),
    ("Start timer for tea steeping 4 minutes", {"duration": "4 minutes", "label": "tea"}),
    ("Timer 7 minutes for rice", {"duration": "7 minutes", "label": "rice"}),
    ("Set 35 minute timer", {"duration": "35 minutes"}),
    ("Nap timer for 20 minutes", {"duration": "20 minutes", "label": "nap"}),
    ("Create meditation timer 10 minutes", {"duration": "10 minutes", "label": "meditation"}),
    ("Timer for cookies 11 minutes", {"duration": "11 minutes", "label": "cookies"}),
    ("Set a half hour timer", {"duration": "30 minutes"}),
    ("Timer 2 hours for roast", {"duration": "2 hours", "label": "roast"}),
    ("Quick timer 45 seconds", {"duration": "45 seconds"}),
    ("Set break timer 15 minutes", {"duration": "15 minutes", "label": "break"}),
    ("Timer for 6 minutes", {"duration": "6 minutes"}),
    ("Bread timer 40 minutes", {"duration": "40 minutes", "label": "bread"}),
    ("Set study timer 50 minutes", {"duration": "50 minutes", "label": "study"}),
    ("Timer 90 minutes for movie", {"duration": "90 minutes", "label": "movie"}),
    ("Start countdown 5 minutes", {"duration": "5 minutes"}),
    ("Set 18 minute timer", {"duration": "18 minutes"}),
    ("Chicken timer for 25 minutes", {"duration": "25 minutes", "label": "chicken"}),
    ("Create timer 1 hour 30 minutes", {"duration": "1 hour 30 minutes"}),
    ("Timer for stretching 8 minutes", {"duration": "8 minutes", "label": "stretching"}),
    ("Set reminder timer 10 minutes", {"duration": "10 minutes", "label": "reminder"}),
    ("Coffee timer 4 minutes", {"duration": "4 minutes", "label": "coffee"}),
    ("Timer 55 minutes", {"duration": "55 minutes"}),
    ("Set game timer 2 hours", {"duration": "2 hours", "label": "game"}),
    ("Quick 30 second countdown", {"duration": "30 seconds"}),
    ("Timer for veggies 9 minutes", {"duration": "9 minutes", "label": "veggies"}),
    ("Set focus timer 45 minutes", {"duration": "45 minutes", "label": "focus"}),
    ("Sauce timer 20 minutes", {"duration": "20 minutes", "label": "sauce"}),
    ("Timer 3 hours", {"duration": "3 hours"}),
    ("Set parking meter reminder 2 hours", {"duration": "2 hours", "label": "parking"}),
    ("Timer for face mask 15 minutes", {"duration": "15 minutes", "label": "face mask"}),
    ("Create 22 minute timer", {"duration": "22 minutes"}),
    ("Timer steaks 6 minutes", {"duration": "6 minutes", "label": "steaks"}),
    ("Set charging timer 1 hour", {"duration": "1 hour", "label": "charging"}),
    ("Baby bottle timer 3 minutes", {"duration": "3 minutes", "label": "bottle"}),
    ("Start 14 minute timer", {"duration": "14 minutes"}),
    ("Set a 5 minute timer", {"duration": "5 minutes"}),
    ("Timer 40 minutes for laundry", {"duration": "40 minutes", "label": "laundry"}),
    ("Start a timer for one hour", {"duration": "1 hour"}),
    ("15 minute timer please", {"duration": "15 minutes"}),
    ("Set timer for 2 minutes brushing teeth", {"duration": "2 minutes", "label": "brushing teeth"}),
    ("Countdown 10 seconds", {"duration": "10 seconds"}),
    ("Set a timer for 3 and a half minutes", {"duration": "3 minutes 30 seconds"}),
    ("Timer for 50 minutes exam", {"duration": "50 minutes", "label": "exam"}),
    ("Start 4 hour timer", {"duration": "4 hours"}),
    ("Set 55 second timer", {"duration": "55 seconds"}),
    ("Timer 25 minutes for work block", {"duration": "25 minutes", "label": "work block"}),
    ("Create a 7 minute timer", {"duration": "7 minutes"}),
    ("Set timer 12 minutes for pasta", {"duration": "12 minutes", "label": "pasta"}),
    ("Timer for 1 minute plank", {"duration": "1 minute", "label": "plank"}),
    ("Start 30 minute timer", {"duration": "30 minutes"}),
    ("Set a timer for 90 seconds", {"duration": "90 seconds"}),
    ("Timer 20 minutes power nap", {"duration": "20 minutes", "label": "power nap"}),
    ("Set timer 45 minutes for decoding", {"duration": "45 minutes", "label": "decoding"}),
    ("Timer for 8 minutes eggs", {"duration": "8 minutes", "label": "eggs"}),
    ("Start 5 hour timer", {"duration": "5 hours"}),
    ("Set 10 second timer", {"duration": "10 seconds"}),
    ("Timer 15 minutes break", {"duration": "15 minutes", "label": "break"}),
    ("Set a timer for 2.5 minutes", {"duration": "2 minutes 30 seconds"}),
    ("Timer for 35 minutes jogging", {"duration": "35 minutes", "label": "jogging"}),
    ("Start 6 minute timer", {"duration": "6 minutes"}),
    ("Set timer 18 minutes", {"duration": "18 minutes"}),
    ("Timer 4 minutes coffee", {"duration": "4 minutes", "label": "coffee"}),
    ("Set a timer for half an hour", {"duration": "30 minutes"}),
    ("Timer for 1 hour 15 minutes", {"duration": "1 hour 15 minutes"}),
    ("Start 45 second timer", {"duration": "45 seconds"}),
    ("Set timer 9 minutes", {"duration": "9 minutes"}),
    ("Timer 3 minutes steeping", {"duration": "3 minutes", "label": "steeping"}),
    ("Set a timer for 12 hours", {"duration": "12 hours"}),
    ("Timer for 5 minutes meditation", {"duration": "5 minutes", "label": "meditation"}),
    ("Start 33 minute timer", {"duration": "33 minutes"}),
    ("Set timer 22 minutes", {"duration": "22 minutes"}),
    ("Timer for 10 minutes reading", {"duration": "10 minutes", "label": "reading"}),
    ("Set a timer for 5 hours", {"duration": "5 hours"}),
    ("Timer 25 minutes cleaning", {"duration": "25 minutes", "label": "cleaning"}),
    ("Start 1 minute timer", {"duration": "1 minute"}),
    ("Set timer 16 minutes", {"duration": "16 minutes"}),
    ("Timer for 60 seconds", {"duration": "60 seconds"}),
    ("Set a timer for 2 hours", {"duration": "2 hours"}),
    ("Timer 28 minutes podcast", {"duration": "28 minutes", "label": "podcast"}),
    ("Start 8 minute timer", {"duration": "8 minutes"}),
    ("Set timer 30 seconds stretch", {"duration": "30 seconds", "label": "stretch"}),
    ("Timer for 7 minutes yoga", {"duration": "7 minutes", "label": "yoga"}),
    ("Set a timer for 10 hours", {"duration": "10 hours"}),
    ("Timer 11 minutes", {"duration": "11 minutes"}),
    ("Start 2 minute timer", {"duration": "2 minutes"}),
]

# ============ SET_ALARM (50 examples) ============
set_alarm_examples = [
    ("Set an alarm for 7am", {"time": "7am"}),
    ("Wake me up at 6:30", {"time": "6:30am"}),
    ("Alarm for 8 o'clock", {"time": "8am"}),
    ("Set alarm 5:45am", {"time": "5:45am"}),
    ("Wake up alarm 7:15", {"time": "7:15am"}),
    ("Set morning alarm 6am", {"time": "6am", "label": "morning"}),
    ("Alarm at 9am for meeting", {"time": "9am", "label": "meeting"}),
    ("Set an alarm for noon", {"time": "12pm"}),
    ("Wake me at 5am", {"time": "5am"}),
    ("Alarm 10:30pm", {"time": "10:30pm"}),
    ("Set alarm for 4:30 in the morning", {"time": "4:30am"}),
    ("Create alarm 7:45am", {"time": "7:45am"}),
    ("Wake up call at 6:15", {"time": "6:15am"}),
    ("Set an 8:30 alarm", {"time": "8:30am"}),
    ("Alarm for tomorrow 7am", {"time": "7am"}),
    ("Set my workout alarm 5:30am", {"time": "5:30am", "label": "workout"}),
    ("Alarm at 11pm for bed", {"time": "11pm", "label": "bedtime"}),
    ("Wake me 6:45", {"time": "6:45am"}),
    ("Set alarm 3pm for pickup", {"time": "3pm", "label": "pickup"}),
    ("Morning alarm 7:30", {"time": "7:30am", "label": "morning"}),
    ("Set an alarm for 2pm", {"time": "2pm"}),
    ("Alarm 6:20am", {"time": "6:20am"}),
    ("Set school alarm 6:30am", {"time": "6:30am", "label": "school"}),
    ("Wake me up at 7:05", {"time": "7:05am"}),
    ("Alarm for 5:15am", {"time": "5:15am"}),
    ("Set lunch reminder alarm noon", {"time": "12pm", "label": "lunch"}),
    ("Alarm at 10am", {"time": "10am"}),
    ("Set early alarm 4am", {"time": "4am"}),
    ("Wake up at quarter to seven", {"time": "6:45am"}),
    ("Alarm for 8am sharp", {"time": "8am"}),
    ("Set nap alarm 3:30pm", {"time": "3:30pm", "label": "nap"}),
    ("Alarm 9:15am", {"time": "9:15am"}),
    ("Set gym alarm 5am", {"time": "5am", "label": "gym"}),
    ("Wake me at 7:20", {"time": "7:20am"}),
    ("Alarm for 6:40am", {"time": "6:40am"}),
    ("Set medication alarm 8pm", {"time": "8pm", "label": "medication"}),
    ("Alarm at 11:30am", {"time": "11:30am"}),
    ("Set 7:55 alarm", {"time": "7:55am"}),
    ("Wake up call 6am", {"time": "6am"}),
    ("Alarm for 4pm meeting", {"time": "4pm", "label": "meeting"}),
    ("Set alarm 5:50am", {"time": "5:50am"}),
    ("Alarm at seven thirty", {"time": "7:30am"}),
    ("Set call alarm 2:30pm", {"time": "2:30pm", "label": "call"}),
    ("Wake me 6:35am", {"time": "6:35am"}),
    ("Alarm for 9:45am", {"time": "9:45am"}),
    ("Set flight alarm 4:15am", {"time": "4:15am", "label": "flight"}),
    ("Alarm at 1pm", {"time": "1pm"}),
    ("Set 6:55 alarm", {"time": "6:55am"}),
    ("Wake me up at eight", {"time": "8am"}),
    ("Alarm 7:10am", {"time": "7:10am"}),
    ("Set alarm for 5:30 tomorrow", {"time": "5:30am", "date": "tomorrow"}),
    ("Wake me up at 9 on Saturday", {"time": "9am", "date": "Saturday"}),
    ("Alarm 8:45pm", {"time": "8:45pm"}),
    ("Set a reminder alarm for 10am", {"time": "10am", "label": "reminder"}),
    ("Wake me at 6:10", {"time": "6:10am"}),
    ("Alarm for 7:50am", {"time": "7:50am"}),
    ("Set alarm 11:15am for brunch", {"time": "11:15am", "label": "brunch"}),
    ("Wake up at 5:05am", {"time": "5:05am"}),
    ("Alarm 1:30pm", {"time": "1:30pm"}),
    ("Set alarm for midnight", {"time": "12am"}),
    ("Wake me up at 7:40", {"time": "7:40am"}),
    ("Alarm for 6:25am", {"time": "6:25am"}),
    ("Set pill alarm 9pm", {"time": "9pm", "label": "pills"}),
    ("Wake me at 8:15", {"time": "8:15am"}),
    ("Alarm 4:45am", {"time": "4:45am"}),
    ("Set alarm 2:15pm call", {"time": "2:15pm", "label": "call"}),
    ("Wake up at 10:30am", {"time": "10:30am"}),
    ("Alarm for 5:55am", {"time": "5:55am"}),
    ("Set laundry alarm 3:45pm", {"time": "3:45pm", "label": "laundry"}),
    ("Wake me up at 6:50", {"time": "6:50am"}),
    ("Alarm 7:25am", {"time": "7:25am"}),
    ("Set alarm for 8:50", {"time": "8:50am"}),
    ("Wake me at 9:30 on Sunday", {"time": "9:30am", "date": "Sunday"}),
    ("Alarm 12:45pm", {"time": "12:45pm"}),
    ("Set alarm 3:20am", {"time": "3:20am"}),
    ("Wake up at 7:12am", {"time": "7:12am"}),
    ("Alarm for 11:50am", {"time": "11:50am"}),
    ("Set gym alarm 4:50am", {"time": "4:50am", "label": "gym"}),
    ("Wake me up at 5:40", {"time": "5:40am"}),
    ("Alarm 6:05am", {"time": "6:05am"}),
    ("Set alarm 10:10am", {"time": "10:10am"}),
    ("Wake me at 8:20", {"time": "8:20am"}),
    ("Alarm for 3:55pm", {"time": "3:55pm"}),
    ("Set alarm 7:35am", {"time": "7:35am"}),
    ("Wake up at 4:25am", {"time": "4:25am"}),
    ("Alarm 1:50pm", {"time": "1:50pm"}),
    ("Set alarm 9:05am", {"time": "9:05am"}),
    ("Wake me up at 6:33", {"time": "6:33am"}),
    ("Alarm 5:25am", {"time": "5:25am"}),
    ("Set alarm for 2:45pm", {"time": "2:45pm"}),
    ("Wake me at 7:45 on Monday", {"time": "7:45am", "date": "Monday"}),
    ("Alarm 10:45pm", {"time": "10:45pm"}),
    ("Set alarm 12:15am", {"time": "12:15am"}),
    ("Wake up at 8:55", {"time": "8:55am"}),
    ("Alarm for 6:12am", {"time": "6:12am"}),
    ("Set alarm 4:10pm", {"time": "4:10pm"}),
    ("Wake me up at 9:10", {"time": "9:10am"}),
    ("Alarm 5:35am", {"time": "5:35am"}),
    ("Set alarm 11:05am", {"time": "11:05am"}),
    ("Wake me at 7:55", {"time": "7:55am"}),
]

# ============ CREATE_CALENDAR_EVENT (50 examples) ============
calendar_examples = [
    ("Schedule a meeting tomorrow at 3pm", {"title": "meeting", "date": "tomorrow", "time": "3pm"}),
    ("Add dentist appointment Friday 2pm", {"title": "dentist appointment", "date": "Friday", "time": "2pm"}),
    ("Create event lunch with John Monday noon", {"title": "lunch with John", "date": "Monday", "time": "12pm"}),
    ("Schedule team standup daily 9am", {"title": "team standup", "time": "9am"}),
    ("Add call with mom Saturday 11am", {"title": "call with mom", "date": "Saturday", "time": "11am"}),
    ("Schedule doctor visit next Tuesday 10am", {"title": "doctor visit", "date": "next Tuesday", "time": "10am"}),
    ("Create meeting with boss at 4pm", {"title": "meeting with boss", "time": "4pm"}),
    ("Add gym session tomorrow 6am", {"title": "gym session", "date": "tomorrow", "time": "6am"}),
    ("Schedule haircut Wednesday 3:30pm", {"title": "haircut", "date": "Wednesday", "time": "3:30pm"}),
    ("Add birthday party Saturday 5pm", {"title": "birthday party", "date": "Saturday", "time": "5pm"}),
    ("Create dinner reservation Friday 7pm", {"title": "dinner reservation", "date": "Friday", "time": "7pm"}),
    ("Schedule oil change Monday morning", {"title": "oil change", "date": "Monday", "time": "morning"}),
    ("Add parent teacher conference Thursday 4pm", {"title": "parent teacher conference", "date": "Thursday", "time": "4pm"}),
    ("Create interview tomorrow 2:30pm", {"title": "interview", "date": "tomorrow", "time": "2:30pm"}),
    ("Schedule vet visit next week", {"title": "vet visit", "date": "next week"}),
    ("Add yoga class Tuesday 7am", {"title": "yoga class", "date": "Tuesday", "time": "7am"}),
    ("Create lunch meeting Wednesday noon", {"title": "lunch meeting", "date": "Wednesday", "time": "12pm"}),
    ("Schedule car service Friday 8am", {"title": "car service", "date": "Friday", "time": "8am"}),
    ("Add movie night Saturday 8pm", {"title": "movie night", "date": "Saturday", "time": "8pm"}),
    ("Create client call Monday 11am", {"title": "client call", "date": "Monday", "time": "11am"}),
    ("Schedule grocery shopping Sunday 10am", {"title": "grocery shopping", "date": "Sunday", "time": "10am"}),
    ("Add concert tickets event Friday 7pm", {"title": "concert", "date": "Friday", "time": "7pm"}),
    ("Create brunch Sunday 11am", {"title": "brunch", "date": "Sunday", "time": "11am"}),
    ("Schedule code review Thursday 2pm", {"title": "code review", "date": "Thursday", "time": "2pm"}),
    ("Add anniversary dinner next Saturday", {"title": "anniversary dinner", "date": "next Saturday"}),
    ("Create project deadline Friday", {"title": "project deadline", "date": "Friday"}),
    ("Schedule flight Tuesday 6am", {"title": "flight", "date": "Tuesday", "time": "6am"}),
    ("Add therapy session Wednesday 3pm", {"title": "therapy session", "date": "Wednesday", "time": "3pm"}),
    ("Create book club meeting Thursday 6pm", {"title": "book club", "date": "Thursday", "time": "6pm"}),
    ("Schedule presentation Monday 10am", {"title": "presentation", "date": "Monday", "time": "10am"}),
    ("Add coffee with Sarah tomorrow 9am", {"title": "coffee with Sarah", "date": "tomorrow", "time": "9am"}),
    ("Create piano lesson Saturday 2pm", {"title": "piano lesson", "date": "Saturday", "time": "2pm"}),
    ("Schedule date night Friday 6:30pm", {"title": "date night", "date": "Friday", "time": "6:30pm"}),
    ("Add soccer practice Tuesday 4pm", {"title": "soccer practice", "date": "Tuesday", "time": "4pm"}),
    ("Create team lunch Wednesday 12:30", {"title": "team lunch", "date": "Wednesday", "time": "12:30pm"}),
    ("Schedule eye exam next month", {"title": "eye exam", "date": "next month"}),
    ("Add game night Saturday 7pm", {"title": "game night", "date": "Saturday", "time": "7pm"}),
    ("Create conference call Friday 9am", {"title": "conference call", "date": "Friday", "time": "9am"}),
    ("Schedule massage Thursday 5pm", {"title": "massage", "date": "Thursday", "time": "5pm"}),
    ("Add study group Sunday 3pm", {"title": "study group", "date": "Sunday", "time": "3pm"}),
    ("Create board meeting Monday 8am", {"title": "board meeting", "date": "Monday", "time": "8am"}),
    ("Schedule wine tasting Saturday", {"title": "wine tasting", "date": "Saturday"}),
    ("Add swimming lessons Wednesday 4:30pm", {"title": "swimming lessons", "date": "Wednesday", "time": "4:30pm"}),
    ("Create networking event Thursday 6pm", {"title": "networking event", "date": "Thursday", "time": "6pm"}),
    ("Schedule pickup from airport Sunday 3pm", {"title": "airport pickup", "date": "Sunday", "time": "3pm"}),
    ("Add dance class Tuesday 7pm", {"title": "dance class", "date": "Tuesday", "time": "7pm"}),
    ("Create all hands meeting Friday 2pm", {"title": "all hands meeting", "date": "Friday", "time": "2pm"}),
    ("Schedule tutoring session Monday 4pm", {"title": "tutoring session", "date": "Monday", "time": "4pm"}),
    ("Add potluck dinner Saturday noon", {"title": "potluck dinner", "date": "Saturday", "time": "12pm"}),
    ("Create sprint planning Monday 9:30am", {"title": "sprint planning", "date": "Monday", "time": "9:30am"}),
    ("Schedule hiking trip Saturday 8am", {"title": "hiking trip", "date": "Saturday", "time": "8am"}),
    ("Add weekly sync Monday 2pm", {"title": "weekly sync", "date": "Monday", "time": "2pm"}),
    ("Create dentist appointment for June 10th", {"title": "dentist appointment", "date": "June 10th"}),
    ("Schedule drinks with friends Friday 8pm", {"title": "drinks with friends", "date": "Friday", "time": "8pm"}),
    ("Add quarterly review next Friday", {"title": "quarterly review", "date": "next Friday"}),
    ("Create workshop Tuesday 10am", {"title": "workshop", "date": "Tuesday", "time": "10am"}),
    ("Schedule family dinner Sunday 5pm", {"title": "family dinner", "date": "Sunday", "time": "5pm"}),
    ("Add car inspection Wednesday 9am", {"title": "car inspection", "date": "Wednesday", "time": "9am"}),
    ("Create gym class Thursday 6pm", {"title": "gym class", "date": "Thursday", "time": "6pm"}),
    ("Schedule marketing meeting Monday 11am", {"title": "marketing meeting", "date": "Monday", "time": "11am"}),
    ("Add vacation start date July 1st", {"title": "vacation start", "date": "July 1st"}),
    ("Create coffee chat tomorrow 10:30", {"title": "coffee chat", "date": "tomorrow", "time": "10:30am"}),
    ("Schedule dog grooming Saturday 11am", {"title": "dog grooming", "date": "Saturday", "time": "11am"}),
    ("Add budget review Friday 3pm", {"title": "budget review", "date": "Friday", "time": "3pm"}),
    ("Create town hall meeting Wednesday 1pm", {"title": "town hall", "date": "Wednesday", "time": "1pm"}),
    ("Schedule tennis match Sunday 9am", {"title": "tennis match", "date": "Sunday", "time": "9am"}),
    ("Add kids concert Thursday 7pm", {"title": "kids concert", "date": "Thursday", "time": "7pm"}),
    ("Create planning session Monday 4:30", {"title": "planning session", "date": "Monday", "time": "4:30pm"}),
    ("Schedule haircut next Tuesday 5pm", {"title": "haircut", "date": "next Tuesday", "time": "5pm"}),
    ("Add volunteer work Saturday morning", {"title": "volunteer work", "date": "Saturday", "time": "morning"}),
    ("Create design review Wednesday 2pm", {"title": "design review", "date": "Wednesday", "time": "2pm"}),
    ("Schedule pickup laundry Friday 5pm", {"title": "pickup laundry", "date": "Friday", "time": "5pm"}),
    ("Add soccer game Sunday 11am", {"title": "soccer game", "date": "Sunday", "time": "11am"}),
    ("Create intro call Thursday 11:30", {"title": "intro call", "date": "Thursday", "time": "11:30am"}),
    ("Schedule brunch next Sunday", {"title": "brunch", "date": "next Sunday"}),
    ("Add mechanic appointment Monday 8am", {"title": "mechanic appointment", "date": "Monday", "time": "8am"}),
    ("Create project kickoff Tuesday 10am", {"title": "project kickoff", "date": "Tuesday", "time": "10am"}),
    ("Schedule yoga Friday 7am", {"title": "yoga", "date": "Friday", "time": "7am"}),
    ("Add dinner with parents Saturday 6pm", {"title": "dinner with parents", "date": "Saturday", "time": "6pm"}),
    ("Create status update Wednesday 9:15", {"title": "status update", "date": "Wednesday", "time": "9:15am"}),
    ("Schedule eye doctor Thursday 4pm", {"title": "eye doctor", "date": "Thursday", "time": "4pm"}),
    ("Add shopping trip Sunday 1pm", {"title": "shopping trip", "date": "Sunday", "time": "1pm"}),
    ("Create strategy meeting Monday 3pm", {"title": "strategy meeting", "date": "Monday", "time": "3pm"}),
    ("Schedule vet appointment Saturday 9:30", {"title": "vet appointment", "date": "Saturday", "time": "9:30am"}),
    ("Add cooking class Friday 7:30pm", {"title": "cooking class", "date": "Friday", "time": "7:30pm"}),
    ("Create standup tomorrow 10am", {"title": "standup", "date": "tomorrow", "time": "10am"}),
    ("Schedule call with accountant Tuesday 11am", {"title": "accountant call", "date": "Tuesday", "time": "11am"}),
    ("Add birthday dinner next Saturday", {"title": "birthday dinner", "date": "next Saturday"}),
    ("Create team outing Friday 4pm", {"title": "team outing", "date": "Friday", "time": "4pm"}),
    ("Schedule house warming Sunday 2pm", {"title": "house warming", "date": "Sunday", "time": "2pm"}),
    ("Add tax deadline April 15th", {"title": "tax deadline", "date": "April 15th"}),
    ("Create client presentation Wednesday 10am", {"title": "client presentation", "date": "Wednesday", "time": "10am"}),
    ("Schedule running club Saturday 7am", {"title": "running club", "date": "Saturday", "time": "7am"}),
    ("Add movie date Friday 9pm", {"title": "movie date", "date": "Friday", "time": "9pm"}),
    ("Create code freeze Monday", {"title": "code freeze", "date": "Monday"}),
    ("Schedule lunch with mentor Tuesday noon", {"title": "lunch with mentor", "date": "Tuesday", "time": "12pm"}),
    ("Add open house Sunday 11am", {"title": "open house", "date": "Sunday", "time": "11am"}),
    ("Create baby shower Saturday 1pm", {"title": "baby shower", "date": "Saturday", "time": "1pm"}),
    ("Schedule interview Thursday 3:30pm", {"title": "interview", "date": "Thursday", "time": "3:30pm"}),
    ("Add webinar Wednesday 12pm", {"title": "webinar", "date": "Wednesday", "time": "12pm"}),
    ("Create retreat weekend next Friday", {"title": "retreat weekend", "date": "next Friday"}),
]

# ============ ADD_TASK (50 examples) ============
task_examples = [
    ('Add buy groceries to my task list', {'text': 'buy groceries'}),
    ('Add to todo list: call mom', {'text': 'call mom'}),
    ('Put pay bills on the task list', {'text': 'pay bills'}),
    ('Add new task: send email', {'text': 'send email'}),
    ('Add to task list: water plants', {'text': 'water plants'}),
    ('Create task pick up dry cleaning', {'text': 'pick up dry cleaning'}),
    ('Add to list: take out trash', {'text': 'take out trash'}),
    ('Add book flight tickets to my to-do list', {'text': 'book flight tickets'}),
    ('Add task: schedule dentist', {'text': 'schedule dentist'}),
    ('Put finish report on my task list', {'text': 'finish report'}),
    ('Add buy birthday gift to my tasks', {'text': 'buy birthday gift'}),
    ('Add to todo list: clean the house', {'text': 'clean the house'}),
    ('Add entry to tasks: water plants', {'text': 'water plants'}),
    ('Add task do laundry', {'text': 'do laundry'}),
    ('Put return library books on the list', {'text': 'return library books'}),
    ('Add renew subscription to task list', {'text': 'renew subscription'}),
    ('Add new task: fix leaky faucet', {'text': 'fix leaky faucet'}),
    ('Add to list: order supplies', {'text': 'order supplies'}),
    ('Create task submit expense report', {'text': 'submit expense report'}),
    ('Add schedule car maintenance to my to-do list', {'text': 'schedule car maintenance'}),
    ('Add task: prescription refill', {'text': 'prescription refill'}),
    ('Put backup computer files on my task list', {'text': 'backup computer files'}),
    ('Add cancel subscription to my tasks', {'text': 'cancel subscription'}),
    ('Add to todo list: review contract', {'text': 'review contract'}),
    ('Add entry to tasks: meal prep', {'text': 'meal prep'}),
    ('Add task update resume', {'text': 'update resume'}),
    ('Put organize closet on the list', {'text': 'organize closet'}),
    ('Add reply to John to task list', {'text': 'reply to John'}),
    ('Add new task: prepare presentation', {'text': 'prepare presentation'}),
    ('Add to list: buy new shoes', {'text': 'buy new shoes'}),
    ('Create task call insurance', {'text': 'call insurance'}),
    ('Add fix broken chair to my to-do list', {'text': 'fix broken chair'}),
    ('Add task: research vacation', {'text': 'research vacation'}),
    ('Put sign permission slip on my task list', {'text': 'sign permission slip'}),
    ('Add change air filters to my tasks', {'text': 'change air filters'}),
    ('Add to todo list: change oil', {'text': 'change oil'}),
    ('Add entry to tasks: buy dog food', {'text': 'buy dog food'}),
    ('Add task clean garage', {'text': 'clean garage'}),
    ('Put follow up with client on the list', {'text': 'follow up with client'}),
    ('Add return Amazon package to task list', {'text': 'return Amazon package'}),
    ('Add new task: charge batteries', {'text': 'charge batteries'}),
    ('Add to list: paint bedroom', {'text': 'paint bedroom'}),
    ('Create task schedule haircut', {'text': 'schedule haircut'}),
    ('Add write thank you notes to my to-do list', {'text': 'write thank you notes'}),
    ('Add task: buy new headphones', {'text': 'buy new headphones'}),
    ('Put water lawn on my task list', {'text': 'water lawn'}),
    ('Add vacuum the car to my tasks', {'text': 'vacuum the car'}),
    ('Add to todo list: file taxes', {'text': 'file taxes'}),
    ('Add entry to tasks: update software', {'text': 'update software'}),
    ('Add task defrost freezer', {'text': 'defrost freezer'}),
    ('Put RSVP to party on the list', {'text': 'RSVP to party'}),
    ('Add buy milk to task list', {'text': 'buy milk'}),
    ('Add new task: call Steve', {'text': 'call Steve'}),
    ('Add to list: clean the kitchen', {'text': 'clean the kitchen'}),
    ('Create task wash the car', {'text': 'wash the car'}),
    ('Add hiking to my to-do list', {'text': 'hiking'}),
    ('Add task: submit the report', {'text': 'submit the report'}),
    ('Put pay the bills on my task list', {'text': 'pay the bills'}),
    ('Add water plants to my tasks', {'text': 'water plants'}),
    ('Add to todo list: project review', {'text': 'project review'}),
    ('Add entry to tasks: buy stamps', {'text': 'buy stamps'}),
    ('Add task text mom back', {'text': 'text mom back'}),
    ('Put schedule doctor appt on the list', {'text': 'schedule doctor appt'}),
    ('Add walk the dog to task list', {'text': 'walk the dog'}),
    ('Add new task: debug the router', {'text': 'debug the router'}),
    ('Add to list: read book', {'text': 'read book'}),
    ('Create task pick up package', {'text': 'pick up package'}),
    ('Add check email to my to-do list', {'text': 'check email'}),
    ('Add task: finish laundry', {'text': 'finish laundry'}),
    ('Put organize desk on my task list', {'text': 'organize desk'}),
    ('Add write documentation to my tasks', {'text': 'write documentation'}),
    ('Add to todo list: buy gift for Sarah', {'text': 'buy gift for Sarah'}),
    ('Add entry to tasks: charge phone', {'text': 'charge phone'}),
    ('Add task check tires', {'text': 'check tires'}),
    ('Put plan weekend trip on the list', {'text': 'plan weekend trip'}),
    ('Add buy coffee beans to task list', {'text': 'buy coffee beans'}),
    ('Add new task: update software', {'text': 'update software'}),
    ('Add to list: take vitamins', {'text': 'take vitamins'}),
    ('Create task pay rent', {'text': 'pay rent'}),
    ('Add clean bathroom to my to-do list', {'text': 'clean bathroom'}),
    ('Add task: mail the letter', {'text': 'mail the letter'}),
    ('Put schedule meeting with team on my task list', {'text': 'schedule meeting with team'}),
    ('Add defrost chicken to my tasks', {'text': 'defrost chicken'}),
    ('Add to todo list: backup photos', {'text': 'backup photos'}),
    ('Add entry to tasks: watch new episode', {'text': 'watch new episode'}),
    ('Add task order pizza', {'text': 'order pizza'}),
    ('Put review PRs on the list', {'text': 'review PRs'}),
    ('Add buy formatting to task list', {'text': 'buy formatting'}),
    ('Add new task: call the bank', {'text': 'call the bank'}),
    ('Add to list: prepare dinner', {'text': 'prepare dinner'}),
    ('Create task sign documents', {'text': 'sign documents'}),
    ('Add cancel membership to my to-do list', {'text': 'cancel membership'}),
    ('Add task: clean windows', {'text': 'clean windows'}),
    ('Put buy toothpaste on my task list', {'text': 'buy toothpaste'}),
    ('Add check mail to my tasks', {'text': 'check mail'}),
    ('Add to todo list: empty dishwasher', {'text': 'empty dishwasher'}),
    ('Add entry to tasks: water the garden', {'text': 'water the garden'}),
    ('Add task buy batteries', {'text': 'buy batteries'}),
    ('Put close the garage on the list', {'text': 'close the garage'}),
    ('Add renew passport to task list', {'text': 'renew passport'}),
    ('Add new task: send birthday card', {'text': 'send birthday card'}),
    ('Add to list: fix the fence', {'text': 'fix the fence'}),
    ('Create task buy apples', {'text': 'buy apples'}),
    ('Add check flight status to my to-do list', {'text': 'check flight status'}),
    ('Add task: print tickets', {'text': 'print tickets'}),
    ('Put call plumber on my task list', {'text': 'call plumber'}),
    ('Add return the shoes to my tasks', {'text': 'return the shoes'}),
]

# ============ WEB_SEARCH (50 examples) ============
search_examples = [
    ("Search for Italian recipes", {"query": "Italian recipes"}),
    ("Look up weather in Tokyo", {"query": "weather in Tokyo"}),
    ("Search how to tie a tie", {"query": "how to tie a tie"}),
    ("Find best restaurants nearby", {"query": "best restaurants nearby"}),
    ("Look up stock price of Apple", {"query": "Apple stock price"}),
    ("Search for flight deals to Paris", {"query": "flight deals to Paris"}),
    ("Find news about tech", {"query": "latest tech news"}),
    ("Search Python tutorials", {"query": "Python tutorials"}),
    ("Look up movie showtimes", {"query": "movie showtimes near me"}),
    ("Find recipe for banana bread", {"query": "banana bread recipe"}),
    ("Search for yoga exercises", {"query": "yoga exercises for beginners"}),
    ("Look up Lakers score", {"query": "Lakers game score"}),
    ("Find hotels in Miami", {"query": "hotels in Miami"}),
    ("Search home workout routines", {"query": "home workout routines"}),
    ("Look up traffic conditions", {"query": "current traffic conditions"}),
    ("Search for gift ideas", {"query": "gift ideas for birthday"}),
    ("Find used cars for sale", {"query": "used cars for sale"}),
    ("Search best laptops 2024", {"query": "best laptops 2024"}),
    ("Look up flu symptoms", {"query": "flu symptoms"}),
    ("Find coffee shops near me", {"query": "coffee shops near me"}),
    ("Search how to make sourdough", {"query": "how to make sourdough bread"}),
    ("Look up currency exchange rates", {"query": "USD to EUR exchange rate"}),
    ("Search for hiking trails", {"query": "hiking trails near me"}),
    ("Find plumbers in my area", {"query": "plumbers near me"}),
    ("Search for DIY furniture projects", {"query": "DIY furniture projects"}),
    ("Look up concert tickets", {"query": "concert tickets near me"}),
    ("Find best pizza in town", {"query": "best pizza in town"}),
    ("Search for online courses", {"query": "online courses programming"}),
    ("Look up book recommendations", {"query": "best books 2024"}),
    ("Search for car insurance quotes", {"query": "car insurance quotes"}),
    ("Find gym memberships", {"query": "gym memberships near me"}),
    ("Search how to fix a flat tire", {"query": "how to fix a flat tire"}),
    ("Look up gardening tips", {"query": "gardening tips for beginners"}),
    ("Find dentists accepting patients", {"query": "dentists accepting new patients"}),
    ("Search for streaming services", {"query": "best streaming services"}),
    ("Look up train schedule", {"query": "train schedule"}),
    ("Search for moving companies", {"query": "moving companies near me"}),
    ("Find pet stores nearby", {"query": "pet stores near me"}),
    ("Search for wedding venues", {"query": "wedding venues near me"}),
    ("Look up tax deductions", {"query": "tax deductions 2024"}),
    ("Find tutors for math", {"query": "math tutors near me"}),
    ("Search for camping gear", {"query": "best camping gear"}),
    ("Look up pharmacy hours", {"query": "CVS pharmacy hours"}),
    ("Find electricians", {"query": "electricians near me"}),
    ("Search for baby names", {"query": "popular baby names 2024"}),
    ("Look up interview tips", {"query": "job interview tips"}),
    ("Search for language learning apps", {"query": "best language learning apps"}),
    ("Find dry cleaners nearby", {"query": "dry cleaners near me"}),
    ("Search for home improvement ideas", {"query": "home improvement ideas"}),
    ("Look up visa requirements", {"query": "visa requirements for Japan"}),
    ("Search for cookie recipes", {"query": "cookie recipes"}),
    ("Find nearby gas stations", {"query": "gas stations near me"}),
    ("Look up population of China", {"query": "population of China"}),
    ("Search how to play chess", {"query": "how to play chess"}),
    ("Find yoga classes online", {"query": "online yoga classes"}),
    ("Search best sci-fi movies", {"query": "best sci-fi movies"}),
    ("Look up weather in London", {"query": "weather in London"}),
    ("Find nearest post office", {"query": "post office near me"}),
    ("Search for vegan restaurants", {"query": "vegan restaurants near me"}),
    ("Look up SpaceX launch", {"query": "next SpaceX launch"}),
    ("Find guitar chords for Wonderwall", {"query": "Wonderwall guitar chords"}),
    ("Search history of Rome", {"query": "history of Rome"}),
    ("Look up Tesla stock", {"query": "Tesla stock price"}),
    ("Find cheap flights to NYC", {"query": "cheap flights to NYC"}),
    ("Search how to knit", {"query": "how to knit for beginners"}),
    ("Look up NBA standings", {"query": "NBA standings"}),
    ("Find best burger places", {"query": "best burger places near me"}),
    ("Search for iPhone reviews", {"query": "iPhone 15 reviews"}),
    ("Look up symptoms of cold", {"query": "cold symptoms"}),
    ("Find nearest hospital", {"query": "nearest hospital"}),
    ("Search how to unclog drain", {"query": "how to unclog drain"}),
    ("Look up USD to CAD", {"query": "USD to CAD exchange rate"}),
    ("Find hiking boots reviews", {"query": "best hiking boots reviews"}),
    ("Search for local events", {"query": "events near me this weekend"}),
    ("Look up movie ratings", {"query": "latest movie ratings"}),
    ("Find car rental agencies", {"query": "car rental agencies near me"}),
    ("Search how to propagate plants", {"query": "how to propagate plants"}),
    ("Look up definition of serendipity", {"query": "define serendipity"}),
    ("Find dog parks nearby", {"query": "dog parks near me"}),
    ("Search best budget phones", {"query": "best budget smartphones"}),
    ("Look up train delays", {"query": "train delays today"}),
    ("Find notary public", {"query": "notary public near me"}),
    ("Search for gluten free pasta", {"query": "gluten free pasta brands"}),
    ("Look up tax filing deadline", {"query": "tax filing deadline"}),
    ("Find recycling center", {"query": "recycling center near me"}),
    ("Search how to clean leather", {"query": "how to clean leather"}),
    ("Look up golden retriever puppies", {"query": "golden retriever puppies for sale"}),
    ("Find 24 hour pharmacy", {"query": "24 hour pharmacy near me"}),
    ("Search for workout clothes", {"query": "best workout clothes"}),
    ("Look up flights to Hawaii", {"query": "flights to Hawaii"}),
    ("Find tailor nearby", {"query": "tailor near me"}),
    ("Search how to meditate", {"query": "how to meditate"}),
    ("Look up celebrity news", {"query": "latest celebrity news"}),
    ("Find hardware store", {"query": "hardware store near me"}),
    ("Search best running shoes", {"query": "best running shoes 2024"}),
    ("Look up chicken soup recipe", {"query": "chicken soup recipe"}),
    ("Find library hours", {"query": "local library hours"}),
    ("Search for travel insurance", {"query": "best travel insurance"}),
    ("Look up weather in Paris", {"query": "weather in Paris"}),
    ("Find coworking spaces", {"query": "coworking spaces near me"}),
    ("Search how to change oil", {"query": "how to change car oil"}),
]

# ============ GET_SYSTEM_INFO (50 examples) ============
system_info_examples = [
    ("How much time is left on my timer?", {}),
    ("What's on my calendar today?", {}),
    ("Do I have any tasks?", {}),
    ("Are any lights on?", {}),
    ("What time is my alarm set for?", {}),
    ("What's the weather?", {}),
    ("Give me a summary of my day", {}),
    ("How many tasks do I have?", {}),
    ("Is the living room light on?", {}),
    ("What's left on my timer?", {}),
    ("Check my calendar for today", {}),
    ("What do I have scheduled?", {}),
    ("Any alarms set?", {}),
    ("What's the temperature?", {}),
    ("Show me my to-do list", {}),
    ("Which lights are on?", {}),
    ("How's the timer doing?", {}),
    ("What events are coming up?", {}),
    ("Tell me about today", {}),
    ("Any tasks pending?", {}),
    ("What's my schedule look like?", {}),
    ("Status of my timer", {}),
    ("Is it going to rain?", {}),
    ("What's the forecast?", {}),
    ("Do I have meetings today?", {}),
    ("How many minutes left on timer?", {}),
    ("What alarms do I have?", {}),
    ("Show my tasks", {}),
    ("Are there any lights off?", {}),
    ("What's happening today?", {}),
    ("Check the timer status", {}),
    ("Any calendar events?", {}),
    ("What's on my list?", {}),
    ("Status of bedroom light", {}),
    ("When is my next alarm?", {}),
    ("What's the weather forecast?", {}),
    ("How's my day looking?", {}),
    ("Pending tasks?", {}),
    ("Timer check", {}),
    ("What's the current temperature?", {}),
    ("My schedule for today", {}),
    ("Any reminders?", {}),
    ("Light status", {}),
    ("When does the timer go off?", {}),
    ("What's my agenda?", {}),
    ("Do I have anything tomorrow?", {}),
    ("Status of the house", {}),
    ("How's the weather outside?", {}),
    ("What tasks are pending?", {}),
    ("System status", {}),
    ("How much battery is left?", {}),
    ("What's running on my computer?", {}),
    ("Check for system updates", {}),
    ("Is the kitchen light still on?", {}),
    ("How many alarms are set?", {}),
    ("What's on the docket today?", {}),
    ("Any timers running?", {}),
    ("Give me a status report", {}),
    ("What's the indoor temperature?", {}),
    ("Do I have any missed calls?", {}),
    ("Check smart home devices", {}),
    ("How many unread emails?", {}),
    ("Is the front door locked?", {}),
    ("What's playing on the speakers?", {}),
    ("Show me active tasks", {}),
    ("Any upcoming birthdays?", {}),
    ("What's the internet speed?", {}),
    ("Check my daily summary", {}),
    ("How much storage is free?", {}),
    ("Is the garage door open?", {}),
    ("What's the date today?", {}),
    ("Show me the weather widget", {}),
    ("Do I have any reminders?", {}),
    ("Check thermostat settings", {}),
    ("How many devices are connected?", {}),
    ("Is the alarm armed?", {}),
    ("What's the humidity level?", {}),
    ("Check for package deliveries", {}),
    ("Show system health", {}),
    ("Any traffic alerts?", {}),
    ("What's the next event?", {}),
    ("Check light brightness", {}),
    ("How many steps today?", {}),
    ("Is the coffee maker on?", {}),
    ("What's on my shopping list?", {}),
    ("Check network status", {}),
    ("Any severe weather alerts?", {}),
    ("Show me the dashboard", {}),
    ("What's my sleep score?", {}),
    ("Check for software updates", {}),
    ("Is the TV on?", {}),
    ("What's the current time zone?", {}),
    ("Check my notifications", {}),
    ("How much data used?", {}),
    ("Is the window open?", {}),
    ("What's the air quality?", {}),
    ("Check printer status", {}),
    ("How many notes do I have?", {}),
    ("Is the robot vacuum running?", {}),
    ("What's the CPU usage?", {}),
    ("Check backup status", {}),
    ("How many photos took today?", {}),
]

# ============ THINKING (50 examples) ============
thinking_examples = [
    "Explain how neural networks learn",
    "Write a Python function to sort a list",
    "Solve this equation: 3x + 7 = 22",
    "Debug this code that has a memory leak",
    "Explain the theory of relativity",
    "Write a SQL query to find duplicates",
    "Calculate the compound interest on $10000",
    "Explain how blockchain works",
    "Write a recursive function for Fibonacci",
    "Analyze the pros and cons of remote work",
    "Explain quantum computing basics",
    "Write a regex to validate emails",
    "Calculate the probability of rolling doubles",
    "Explain the difference between TCP and UDP",
    "Write an algorithm for binary search",
    "Analyze this stock's performance",
    "Explain machine learning algorithms",
    "Write a function to detect palindromes",
    "Calculate the area of an irregular shape",
    "Explain how encryption works",
    "Write a class for a linked list",
    "Analyze this business problem",
    "Explain the immune system",
    "Write unit tests for this function",
    "Calculate the optimal route",
    "Explain cryptocurrency mining",
    "Write a parser for JSON",
    "Analyze this dataset",
    "Explain photosynthesis in detail",
    "Write an API endpoint",
    "Calculate mortgage payments",
    "Explain how vaccines work",
    "Write a sorting algorithm",
    "Analyze this legal contract",
    "Explain climate change science",
    "Write a web scraper",
    "Calculate return on investment",
    "Explain supply chain logistics",
    "Write a state machine",
    "Analyze this chemical reaction",
    "Explain how GPS works",
    "Write a cache implementation",
    "Calculate statistical significance",
    "Explain the electoral college",
    "Write a database schema",
    "Analyze this poem's meaning",
    "Explain how MRI machines work",
    "Write a compression algorithm",
    "Calculate depreciation",
    "Explain the scientific method",
    "Describe how a car engine works",
    "Write a biography of Albert Einstein",
    "Solve the traveling salesman problem",
    "Explain the plot of Inception",
    "Write a poem about the ocean",
    "Calculate the volume of a sphere",
    "Explain the history of the internet",
    "Write a Javascript function to fetch data",
    "Analyze the themes in To Kill a Mockingbird",
    "Explain how solar panels work",
    "Write a C++ program for printing hello world",
    "Calculate the trajectory of a projectile",
    "Explain the French Revolution",
    "Write a stored procedure in SQL",
    "Analyze the impact of social media",
    "Explain the theory of evolution",
    "Write a bash script to backup files",
    "Calculate the distance between two coordinates",
    "Explain how airplanes fly",
    "Write a short story about time travel",
    "Analyze the causes of the Great Depression",
    "Explain the basics of economics",
    "Write a recipe for chocolate cake",
    "Calculate the factorial of 10",
    "Explain the water cycle",
    "Write a review of the latest iPhone",
    "Analyze the lyrics of Bohemian Rhapsody",
    "Explain how 3D printing works",
    "Write a letter to the editor",
    "Calculate the mean and standard deviation",
    "Explain the structure of an atom",
    "Write a marketing plan for a new product",
    "Analyze current geopolitical tensions",
    "Explain the rules of cricket",
    "Write a Python script for web scraping",
    "Calculate the energy of a photon",
    "Explain the human digestive system",
    "Write a resignation letter",
    "Analyze the color theory in art",
    "Explain how nuclear reactors work",
    "Write a critique of a movie",
    "Calculate the roots of a quadratic equation",
    "Explain the significance of DNA",
    "Write a speech for a wedding",
    "Analyze the trends in fashion",
    "Explain how wireless charging works",
    "Write a HTML/CSS template",
    "Calculate the odds of winning lottery",
    "Explain the Big Bang theory",
    "Write a comparison of iOS and Android",
    "Analyze the ethics of AI",
]

# ============ NONTHINKING (50 examples) ============
nonthinking_examples = [
    "Hello",
    "Hi there",
    "Good morning",
    "How are you?",
    "What's the capital of France?",
    "Who wrote Harry Potter?",
    "What year did WWII end?",
    "What color is the sky?",
    "How many states in the USA?",
    "Who is the CEO of Tesla?",
    "What's 2 + 2?",
    "Thanks",
    "Thank you so much",
    "Goodbye",
    "See you later",
    "What day is it?",
    "Who invented the telephone?",
    "What's the largest ocean?",
    "How many continents are there?",
    "What language is spoken in Brazil?",
    "Hey",
    "What's up?",
    "Good evening",
    "Nice to meet you",
    "What's your name?",
    "Who painted the Mona Lisa?",
    "What's the speed of light?",
    "When is Christmas?",
    "What's the tallest mountain?",
    "Who discovered penicillin?",
    "You're welcome",
    "No problem",
    "Good night",
    "Have a nice day",
    "What time is it?",
    "Who is the president?",
    "What's the currency of Japan?",
    "How many days in a week?",
    "What's the chemical symbol for gold?",
    "Who wrote 1984?",
    "Greetings",
    "Howdy",
    "What's going on?",
    "I'm doing well",
    "Tell me a joke",
    "Define apple",
    "What's the opposite of hot?",
    "Name a planet",
    "What's the boiling point of water?",
    "Who is Mickey Mouse?",
    "What's your favorite color?",
    "How old are you?",
    "Do you like music?",
    "What's the capital of Germany?",
    "Who won the Super Bowl?",
    "What is a cat?",
    "How many legs does a spider have?",
    "What's the fastest animal?",
    "Who is the president of France?",
    "What is the moon made of?",
    "How do you say hello in Spanish?",
    "What is 10 plus 5?",
    "Who discovered America?",
    "What is the color of grass?",
    "How many hours in a day?",
    "What is a computer?",
    "Who is Batman?",
    "What smells good?",
    "How high is Mount Everest?",
    "What is water made of?",
    "Who wrote Romeo and Juliet?",
    "What is the largest country?",
    "How many fingers do humans have?",
    "What is a phone?",
    "Who is the queen of England?",
    "What is ice?",
    "How do birds fly?",
    "What is the sun?",
    "Who is famous?",
    "What is a book?",
    "How much is a dollar?",
    "What is a car?",
    "Who is innovative?",
    "What is a tree?",
    "How deep is the ocean?",
    "What is a house?",
    "Who is smart?",
    "What is fire?",
    "How fast is a cheetah?",
    "What is a cloud?",
    "Who is kind?",
    "What is a dog?",
    "How long is a year?",
    "What is a star?",
    "Who is strong?",
    "What is a flower?",
    "How loud is a concert?",
    "What is a movie?",
    "Who is funny?",
    "What is a game?",
    "How sweet is sugar?",
]

# Generate all examples
all_examples = []

# Add control_light
for prompt, args in control_light_examples:
    all_examples.append(make_example(prompt, "control_light", args))

# Add set_timer
for prompt, args in set_timer_examples:
    all_examples.append(make_example(prompt, "set_timer", args))

# Add set_alarm
for prompt, args in set_alarm_examples:
    all_examples.append(make_example(prompt, "set_alarm", args))

# Add calendar
for prompt, args in calendar_examples:
    all_examples.append(make_example(prompt, "create_calendar_event", args))

# Add tasks
for prompt, args in task_examples:
    all_examples.append(make_example(prompt, "add_task", args))

# Add search
for prompt, args in search_examples:
    all_examples.append(make_example(prompt, "web_search", args))

# Add system_info
for prompt, args in system_info_examples:
    all_examples.append(make_example(prompt, "get_system_info", args))

# Add thinking
for prompt in thinking_examples:
    all_examples.append(make_example(prompt, "thinking", {"prompt": prompt}))

# Add nonthinking
for prompt in nonthinking_examples:
    all_examples.append(make_example(prompt, "nonthinking", {"prompt": prompt}))

# Shuffle
random.seed(42)
random.shuffle(all_examples)

# Write to file
with open("training_dataset_functions.jsonl", "w") as f:
    for ex in all_examples:
        f.write(json.dumps(ex) + "\n")

print(f"Generated {len(all_examples)} training examples")
print("Saved to training_dataset_functions.jsonl")
