"""
Generate training dataset for function calling model.
Creates 50 examples per function (9 functions = 450 total).
"""
import json
import random

# Tool definitions (shared across all examples)
TOOLS = [
    {"type": "function", "function": {"name": "control_light", "description": "Control smart lights - turn on, off, dim, or change color", "parameters": {"type": "object", "properties": {"action": {"type": "string"}, "device_name": {"type": "string"}, "brightness": {"type": "integer"}, "color": {"type": "string"}}, "required": ["action"]}}},
    {"type": "function", "function": {"name": "set_timer", "description": "Set a countdown timer", "parameters": {"type": "object", "properties": {"duration": {"type": "string"}, "label": {"type": "string"}}, "required": ["duration"]}}},
    {"type": "function", "function": {"name": "set_alarm", "description": "Set an alarm for a specific time", "parameters": {"type": "object", "properties": {"time": {"type": "string"}, "label": {"type": "string"}}, "required": ["time"]}}},
    {"type": "function", "function": {"name": "create_calendar_event", "description": "Create a calendar event", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "date": {"type": "string"}, "time": {"type": "string"}, "duration": {"type": "integer"}}, "required": ["title"]}}},
    {"type": "function", "function": {"name": "add_task", "description": "Add a task to the to-do list", "parameters": {"type": "object", "properties": {"text": {"type": "string"}, "priority": {"type": "string"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "web_search", "description": "Search the web for information", "parameters": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}}},
    {"type": "function", "function": {"name": "get_system_info", "description": "Get current system state including timers, calendar, tasks, devices, and weather", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "thinking", "description": "Use for complex queries requiring reasoning, math, coding, or multi-step analysis", "parameters": {"type": "object", "properties": {"prompt": {"type": "string"}}, "required": ["prompt"]}}},
    {"type": "function", "function": {"name": "nonthinking", "description": "Use for simple queries, greetings, factual questions not requiring deep reasoning", "parameters": {"type": "object", "properties": {"prompt": {"type": "string"}}, "required": ["prompt"]}}}
]

SYSTEM_MSG = "You are a model that can do function calling with the following functions"

def make_example(user_content, func_name, args):
    return {
        "messages": [
            {"role": "developer", "content": SYSTEM_MSG},
            {"role": "user", "content": user_content},
            {"role": "assistant", "tool_calls": [{"type": "function", "function": {"name": func_name, "arguments": args}}]}
        ],
        "tools": TOOLS
    }

# ============ CONTROL_LIGHT (50 examples) ============
control_light_examples = [
    ("Turn on the living room lights", {"action": "on", "device_name": "living room"}),
    ("Turn off the bedroom light", {"action": "off", "device_name": "bedroom"}),
    ("Dim the kitchen lights to 50%", {"action": "dim", "device_name": "kitchen", "brightness": 50}),
    ("Switch on all the lights", {"action": "on", "device_name": "all"}),
    ("Make the office light blue", {"action": "on", "device_name": "office", "color": "blue"}),
    ("Set the bathroom light to 25%", {"action": "dim", "device_name": "bathroom", "brightness": 25}),
    ("Toggle the hallway lights", {"action": "toggle", "device_name": "hallway"}),
    ("Lights off everywhere", {"action": "off", "device_name": "all"}),
    ("Change the living room to warm white", {"action": "on", "device_name": "living room", "color": "warm white"}),
    ("Set brightness to full in the garage", {"action": "dim", "device_name": "garage", "brightness": 100}),
    ("Turn the porch light on", {"action": "on", "device_name": "porch"}),
    ("Kill the lights in the den", {"action": "off", "device_name": "den"}),
    ("Brighten the dining room", {"action": "dim", "device_name": "dining room", "brightness": 100}),
    ("Set bedroom to red", {"action": "on", "device_name": "bedroom", "color": "red"}),
    ("Lower the office lights to 30", {"action": "dim", "device_name": "office", "brightness": 30}),
    ("Lights on in basement", {"action": "on", "device_name": "basement"}),
    ("Switch off kitchen light", {"action": "off", "device_name": "kitchen"}),
    ("Make it brighter in here", {"action": "dim", "device_name": "current room", "brightness": 80}),
    ("Dim all lights to 40%", {"action": "dim", "device_name": "all", "brightness": 40}),
    ("Set the nursery to soft pink", {"action": "on", "device_name": "nursery", "color": "pink"}),
    ("Turn on lamp", {"action": "on", "device_name": "lamp"}),
    ("Shut off the desk light", {"action": "off", "device_name": "desk"}),
    ("Bedroom lights at half", {"action": "dim", "device_name": "bedroom", "brightness": 50}),
    ("Change color to green in kids room", {"action": "on", "device_name": "kids room", "color": "green"}),
    ("Maximize brightness in study", {"action": "dim", "device_name": "study", "brightness": 100}),
    ("Turn off outside lights", {"action": "off", "device_name": "outside"}),
    ("Switch the attic light on", {"action": "on", "device_name": "attic"}),
    ("Dim patio lights", {"action": "dim", "device_name": "patio", "brightness": 40}),
    ("Set all lights to cool white", {"action": "on", "device_name": "all", "color": "cool white"}),
    ("Make the closet light brighter", {"action": "dim", "device_name": "closet", "brightness": 75}),
    ("Lights to 10% in master bedroom", {"action": "dim", "device_name": "master bedroom", "brightness": 10}),
    ("Turn on reading lamp", {"action": "on", "device_name": "reading lamp"}),
    ("Office to daylight mode", {"action": "on", "device_name": "office", "color": "daylight"}),
    ("Kill all the lights", {"action": "off", "device_name": "all"}),
    ("Set movie mode lighting", {"action": "dim", "device_name": "living room", "brightness": 20}),
    ("Bathroom at full brightness", {"action": "dim", "device_name": "bathroom", "brightness": 100}),
    ("Purple light in gaming room", {"action": "on", "device_name": "gaming room", "color": "purple"}),
    ("Lower all lights", {"action": "dim", "device_name": "all", "brightness": 30}),
    ("Switch on the ceiling fan light", {"action": "on", "device_name": "ceiling fan"}),
    ("Turn off stairway lights", {"action": "off", "device_name": "stairway"}),
    ("Entryway light on", {"action": "on", "device_name": "entryway"}),
    ("Dim the table lamp to 60", {"action": "dim", "device_name": "table lamp", "brightness": 60}),
    ("Set accent lights to orange", {"action": "on", "device_name": "accent", "color": "orange"}),
    ("Guest room lights off", {"action": "off", "device_name": "guest room"}),
    ("Brighten up the workspace", {"action": "dim", "device_name": "workspace", "brightness": 90}),
    ("Night light on", {"action": "on", "device_name": "night light"}),
    ("Set laundry room to 50%", {"action": "dim", "device_name": "laundry room", "brightness": 50}),
    ("Yellow lights in sunroom", {"action": "on", "device_name": "sunroom", "color": "yellow"}),
    ("Mudroom light off", {"action": "off", "device_name": "mudroom"}),
    ("Front porch to warm", {"action": "on", "device_name": "front porch", "color": "warm"}),
]

# ============ SET_TIMER (50 examples) ============
set_timer_examples = [
    ("Set a timer for 10 minutes", {"duration": "10 minutes"}),
    ("Timer for 5 mins", {"duration": "5 minutes"}),
    ("Set a 30 second timer", {"duration": "30 seconds"}),
    ("Start a one hour timer", {"duration": "1 hour"}),
    ("Timer 15 minutes for eggs", {"duration": "15 minutes", "label": "eggs"}),
    ("Set pasta timer 8 minutes", {"duration": "8 minutes", "label": "pasta"}),
    ("Create a timer for 45 minutes", {"duration": "45 minutes"}),
    ("Set a 2 minute timer", {"duration": "2 minutes"}),
    ("Timer for laundry 1 hour", {"duration": "1 hour", "label": "laundry"}),
    ("Start 20 minute workout timer", {"duration": "20 minutes", "label": "workout"}),
    ("Set timer 3 minutes", {"duration": "3 minutes"}),
    ("Pizza timer 12 minutes", {"duration": "12 minutes", "label": "pizza"}),
    ("Timer for 25 minutes pomodoro", {"duration": "25 minutes", "label": "pomodoro"}),
    ("Set a quick 1 minute timer", {"duration": "1 minute"}),
    ("90 second timer please", {"duration": "90 seconds"}),
    ("Start timer for tea steeping 4 minutes", {"duration": "4 minutes", "label": "tea"}),
    ("Timer 7 minutes for rice", {"duration": "7 minutes", "label": "rice"}),
    ("Set 35 minute timer", {"duration": "35 minutes"}),
    ("Nap timer for 20 minutes", {"duration": "20 minutes", "label": "nap"}),
    ("Create meditation timer 10 minutes", {"duration": "10 minutes", "label": "meditation"}),
    ("Timer for cookies 11 minutes", {"duration": "11 minutes", "label": "cookies"}),
    ("Set a half hour timer", {"duration": "30 minutes"}),
    ("Timer 2 hours for roast", {"duration": "2 hours", "label": "roast"}),
    ("Quick timer 45 seconds", {"duration": "45 seconds"}),
    ("Set break timer 15 minutes", {"duration": "15 minutes", "label": "break"}),
    ("Timer for 6 minutes", {"duration": "6 minutes"}),
    ("Bread timer 40 minutes", {"duration": "40 minutes", "label": "bread"}),
    ("Set study timer 50 minutes", {"duration": "50 minutes", "label": "study"}),
    ("Timer 90 minutes for movie", {"duration": "90 minutes", "label": "movie"}),
    ("Start countdown 5 minutes", {"duration": "5 minutes"}),
    ("Set 18 minute timer", {"duration": "18 minutes"}),
    ("Chicken timer for 25 minutes", {"duration": "25 minutes", "label": "chicken"}),
    ("Create timer 1 hour 30 minutes", {"duration": "1 hour 30 minutes"}),
    ("Timer for stretching 8 minutes", {"duration": "8 minutes", "label": "stretching"}),
    ("Set reminder timer 10 minutes", {"duration": "10 minutes", "label": "reminder"}),
    ("Coffee timer 4 minutes", {"duration": "4 minutes", "label": "coffee"}),
    ("Timer 55 minutes", {"duration": "55 minutes"}),
    ("Set game timer 2 hours", {"duration": "2 hours", "label": "game"}),
    ("Quick 30 second countdown", {"duration": "30 seconds"}),
    ("Timer for veggies 9 minutes", {"duration": "9 minutes", "label": "veggies"}),
    ("Set focus timer 45 minutes", {"duration": "45 minutes", "label": "focus"}),
    ("Sauce timer 20 minutes", {"duration": "20 minutes", "label": "sauce"}),
    ("Timer 3 hours", {"duration": "3 hours"}),
    ("Set parking meter reminder 2 hours", {"duration": "2 hours", "label": "parking"}),
    ("Timer for face mask 15 minutes", {"duration": "15 minutes", "label": "face mask"}),
    ("Create 22 minute timer", {"duration": "22 minutes"}),
    ("Timer steaks 6 minutes", {"duration": "6 minutes", "label": "steaks"}),
    ("Set charging timer 1 hour", {"duration": "1 hour", "label": "charging"}),
    ("Baby bottle timer 3 minutes", {"duration": "3 minutes", "label": "bottle"}),
    ("Start 14 minute timer", {"duration": "14 minutes"}),
]

# ============ SET_ALARM (50 examples) ============
set_alarm_examples = [
    ("Set an alarm for 7am", {"time": "7am"}),
    ("Wake me up at 6:30", {"time": "6:30am"}),
    ("Alarm for 8 o'clock", {"time": "8am"}),
    ("Set alarm 5:45am", {"time": "5:45am"}),
    ("Wake up alarm 7:15", {"time": "7:15am"}),
    ("Set morning alarm 6am", {"time": "6am", "label": "morning"}),
    ("Alarm at 9am for meeting", {"time": "9am", "label": "meeting"}),
    ("Set an alarm for noon", {"time": "12pm"}),
    ("Wake me at 5am", {"time": "5am"}),
    ("Alarm 10:30pm", {"time": "10:30pm"}),
    ("Set alarm for 4:30 in the morning", {"time": "4:30am"}),
    ("Create alarm 7:45am", {"time": "7:45am"}),
    ("Wake up call at 6:15", {"time": "6:15am"}),
    ("Set an 8:30 alarm", {"time": "8:30am"}),
    ("Alarm for tomorrow 7am", {"time": "7am"}),
    ("Set my workout alarm 5:30am", {"time": "5:30am", "label": "workout"}),
    ("Alarm at 11pm for bed", {"time": "11pm", "label": "bedtime"}),
    ("Wake me 6:45", {"time": "6:45am"}),
    ("Set alarm 3pm for pickup", {"time": "3pm", "label": "pickup"}),
    ("Morning alarm 7:30", {"time": "7:30am", "label": "morning"}),
    ("Set an alarm for 2pm", {"time": "2pm"}),
    ("Alarm 6:20am", {"time": "6:20am"}),
    ("Set school alarm 6:30am", {"time": "6:30am", "label": "school"}),
    ("Wake me up at 7:05", {"time": "7:05am"}),
    ("Alarm for 5:15am", {"time": "5:15am"}),
    ("Set lunch reminder alarm noon", {"time": "12pm", "label": "lunch"}),
    ("Alarm at 10am", {"time": "10am"}),
    ("Set early alarm 4am", {"time": "4am"}),
    ("Wake up at quarter to seven", {"time": "6:45am"}),
    ("Alarm for 8am sharp", {"time": "8am"}),
    ("Set nap alarm 3:30pm", {"time": "3:30pm", "label": "nap"}),
    ("Alarm 9:15am", {"time": "9:15am"}),
    ("Set gym alarm 5am", {"time": "5am", "label": "gym"}),
    ("Wake me at 7:20", {"time": "7:20am"}),
    ("Alarm for 6:40am", {"time": "6:40am"}),
    ("Set medication alarm 8pm", {"time": "8pm", "label": "medication"}),
    ("Alarm at 11:30am", {"time": "11:30am"}),
    ("Set 7:55 alarm", {"time": "7:55am"}),
    ("Wake up call 6am", {"time": "6am"}),
    ("Alarm for 4pm meeting", {"time": "4pm", "label": "meeting"}),
    ("Set alarm 5:50am", {"time": "5:50am"}),
    ("Alarm at seven thirty", {"time": "7:30am"}),
    ("Set call alarm 2:30pm", {"time": "2:30pm", "label": "call"}),
    ("Wake me 6:35am", {"time": "6:35am"}),
    ("Alarm for 9:45am", {"time": "9:45am"}),
    ("Set flight alarm 4:15am", {"time": "4:15am", "label": "flight"}),
    ("Alarm at 1pm", {"time": "1pm"}),
    ("Set 6:55 alarm", {"time": "6:55am"}),
    ("Wake me up at eight", {"time": "8am"}),
    ("Alarm 7:10am", {"time": "7:10am"}),
]

# ============ CREATE_CALENDAR_EVENT (50 examples) ============
calendar_examples = [
    ("Schedule a meeting tomorrow at 3pm", {"title": "meeting", "date": "tomorrow", "time": "3pm"}),
    ("Add dentist appointment Friday 2pm", {"title": "dentist appointment", "date": "Friday", "time": "2pm"}),
    ("Create event lunch with John Monday noon", {"title": "lunch with John", "date": "Monday", "time": "12pm"}),
    ("Schedule team standup daily 9am", {"title": "team standup", "time": "9am"}),
    ("Add call with mom Saturday 11am", {"title": "call with mom", "date": "Saturday", "time": "11am"}),
    ("Schedule doctor visit next Tuesday 10am", {"title": "doctor visit", "date": "next Tuesday", "time": "10am"}),
    ("Create meeting with boss at 4pm", {"title": "meeting with boss", "time": "4pm"}),
    ("Add gym session tomorrow 6am", {"title": "gym session", "date": "tomorrow", "time": "6am"}),
    ("Schedule haircut Wednesday 3:30pm", {"title": "haircut", "date": "Wednesday", "time": "3:30pm"}),
    ("Add birthday party Saturday 5pm", {"title": "birthday party", "date": "Saturday", "time": "5pm"}),
    ("Create dinner reservation Friday 7pm", {"title": "dinner reservation", "date": "Friday", "time": "7pm"}),
    ("Schedule oil change Monday morning", {"title": "oil change", "date": "Monday", "time": "morning"}),
    ("Add parent teacher conference Thursday 4pm", {"title": "parent teacher conference", "date": "Thursday", "time": "4pm"}),
    ("Create interview tomorrow 2:30pm", {"title": "interview", "date": "tomorrow", "time": "2:30pm"}),
    ("Schedule vet visit next week", {"title": "vet visit", "date": "next week"}),
    ("Add yoga class Tuesday 7am", {"title": "yoga class", "date": "Tuesday", "time": "7am"}),
    ("Create lunch meeting Wednesday noon", {"title": "lunch meeting", "date": "Wednesday", "time": "12pm"}),
    ("Schedule car service Friday 8am", {"title": "car service", "date": "Friday", "time": "8am"}),
    ("Add movie night Saturday 8pm", {"title": "movie night", "date": "Saturday", "time": "8pm"}),
    ("Create client call Monday 11am", {"title": "client call", "date": "Monday", "time": "11am"}),
    ("Schedule grocery shopping Sunday 10am", {"title": "grocery shopping", "date": "Sunday", "time": "10am"}),
    ("Add concert tickets event Friday 7pm", {"title": "concert", "date": "Friday", "time": "7pm"}),
    ("Create brunch Sunday 11am", {"title": "brunch", "date": "Sunday", "time": "11am"}),
    ("Schedule code review Thursday 2pm", {"title": "code review", "date": "Thursday", "time": "2pm"}),
    ("Add anniversary dinner next Saturday", {"title": "anniversary dinner", "date": "next Saturday"}),
    ("Create project deadline Friday", {"title": "project deadline", "date": "Friday"}),
    ("Schedule flight Tuesday 6am", {"title": "flight", "date": "Tuesday", "time": "6am"}),
    ("Add therapy session Wednesday 3pm", {"title": "therapy session", "date": "Wednesday", "time": "3pm"}),
    ("Create book club meeting Thursday 6pm", {"title": "book club", "date": "Thursday", "time": "6pm"}),
    ("Schedule presentation Monday 10am", {"title": "presentation", "date": "Monday", "time": "10am"}),
    ("Add coffee with Sarah tomorrow 9am", {"title": "coffee with Sarah", "date": "tomorrow", "time": "9am"}),
    ("Create piano lesson Saturday 2pm", {"title": "piano lesson", "date": "Saturday", "time": "2pm"}),
    ("Schedule date night Friday 6:30pm", {"title": "date night", "date": "Friday", "time": "6:30pm"}),
    ("Add soccer practice Tuesday 4pm", {"title": "soccer practice", "date": "Tuesday", "time": "4pm"}),
    ("Create team lunch Wednesday 12:30", {"title": "team lunch", "date": "Wednesday", "time": "12:30pm"}),
    ("Schedule eye exam next month", {"title": "eye exam", "date": "next month"}),
    ("Add game night Saturday 7pm", {"title": "game night", "date": "Saturday", "time": "7pm"}),
    ("Create conference call Friday 9am", {"title": "conference call", "date": "Friday", "time": "9am"}),
    ("Schedule massage Thursday 5pm", {"title": "massage", "date": "Thursday", "time": "5pm"}),
    ("Add study group Sunday 3pm", {"title": "study group", "date": "Sunday", "time": "3pm"}),
    ("Create board meeting Monday 8am", {"title": "board meeting", "date": "Monday", "time": "8am"}),
    ("Schedule wine tasting Saturday", {"title": "wine tasting", "date": "Saturday"}),
    ("Add swimming lessons Wednesday 4:30pm", {"title": "swimming lessons", "date": "Wednesday", "time": "4:30pm"}),
    ("Create networking event Thursday 6pm", {"title": "networking event", "date": "Thursday", "time": "6pm"}),
    ("Schedule pickup from airport Sunday 3pm", {"title": "airport pickup", "date": "Sunday", "time": "3pm"}),
    ("Add dance class Tuesday 7pm", {"title": "dance class", "date": "Tuesday", "time": "7pm"}),
    ("Create all hands meeting Friday 2pm", {"title": "all hands meeting", "date": "Friday", "time": "2pm"}),
    ("Schedule tutoring session Monday 4pm", {"title": "tutoring session", "date": "Monday", "time": "4pm"}),
    ("Add potluck dinner Saturday noon", {"title": "potluck dinner", "date": "Saturday", "time": "12pm"}),
    ("Create sprint planning Monday 9:30am", {"title": "sprint planning", "date": "Monday", "time": "9:30am"}),
]

# ============ ADD_TASK (50 examples) ============
task_examples = [
    ("Add buy groceries to my list", {"text": "buy groceries"}),
    ("Remind me to call mom", {"text": "call mom"}),
    ("Add pick up dry cleaning to tasks", {"text": "pick up dry cleaning"}),
    ("Put pay bills on my todo", {"text": "pay bills"}),
    ("Add task send email to boss", {"text": "send email to boss"}),
    ("Remember to take out trash", {"text": "take out trash"}),
    ("Add book flight tickets to list", {"text": "book flight tickets"}),
    ("Task schedule dentist", {"text": "schedule dentist"}),
    ("Add finish report to todos", {"text": "finish report"}),
    ("Remind me to buy birthday gift", {"text": "buy birthday gift"}),
    ("Add clean the house", {"text": "clean the house"}),
    ("Put water plants on list", {"text": "water plants"}),
    ("Task do laundry", {"text": "do laundry"}),
    ("Add return library books", {"text": "return library books"}),
    ("Remind me to renew subscription", {"text": "renew subscription"}),
    ("Add fix leaky faucet to tasks", {"text": "fix leaky faucet"}),
    ("Put order supplies on todo", {"text": "order supplies"}),
    ("Task submit expense report", {"text": "submit expense report"}),
    ("Add schedule car maintenance", {"text": "schedule car maintenance"}),
    ("Remind me about prescription refill", {"text": "prescription refill"}),
    ("Add backup computer files", {"text": "backup computer files"}),
    ("Put cancel subscription on list", {"text": "cancel subscription"}),
    ("Task review contract", {"text": "review contract"}),
    ("Add meal prep for week", {"text": "meal prep for week"}),
    ("Remind me to update resume", {"text": "update resume"}),
    ("Add organize closet to todos", {"text": "organize closet"}),
    ("Put reply to John on list", {"text": "reply to John"}),
    ("Task prepare presentation", {"text": "prepare presentation"}),
    ("Add buy new shoes", {"text": "buy new shoes"}),
    ("Remind me to call insurance", {"text": "call insurance"}),
    ("Add fix broken chair", {"text": "fix broken chair"}),
    ("Put research vacation on todo", {"text": "research vacation"}),
    ("Task sign permission slip", {"text": "sign permission slip"}),
    ("Add change air filters", {"text": "change air filters"}),
    ("Remind me about oil change", {"text": "schedule oil change"}),
    ("Add buy dog food to list", {"text": "buy dog food"}),
    ("Put clean garage on tasks", {"text": "clean garage"}),
    ("Task follow up with client", {"text": "follow up with client"}),
    ("Add return Amazon package", {"text": "return Amazon package"}),
    ("Remind me to charge batteries", {"text": "charge batteries"}),
    ("Add paint bedroom to todos", {"text": "paint bedroom"}),
    ("Put schedule haircut on list", {"text": "schedule haircut"}),
    ("Task write thank you notes", {"text": "write thank you notes"}),
    ("Add buy new headphones", {"text": "buy new headphones"}),
    ("Remind me to water lawn", {"text": "water lawn"}),
    ("Add vacuum the car", {"text": "vacuum the car"}),
    ("Put file taxes on todo", {"text": "file taxes"}),
    ("Task update software", {"text": "update software"}),
    ("Add defrost freezer", {"text": "defrost freezer"}),
    ("Remind me RSVP to party", {"text": "RSVP to party"}),
]

# ============ WEB_SEARCH (50 examples) ============
search_examples = [
    ("Search for Italian recipes", {"query": "Italian recipes"}),
    ("Look up weather in Tokyo", {"query": "weather in Tokyo"}),
    ("Search how to tie a tie", {"query": "how to tie a tie"}),
    ("Find best restaurants nearby", {"query": "best restaurants nearby"}),
    ("Look up stock price of Apple", {"query": "Apple stock price"}),
    ("Search for flight deals to Paris", {"query": "flight deals to Paris"}),
    ("Find news about tech", {"query": "latest tech news"}),
    ("Search Python tutorials", {"query": "Python tutorials"}),
    ("Look up movie showtimes", {"query": "movie showtimes near me"}),
    ("Find recipe for banana bread", {"query": "banana bread recipe"}),
    ("Search for yoga exercises", {"query": "yoga exercises for beginners"}),
    ("Look up Lakers score", {"query": "Lakers game score"}),
    ("Find hotels in Miami", {"query": "hotels in Miami"}),
    ("Search home workout routines", {"query": "home workout routines"}),
    ("Look up traffic conditions", {"query": "current traffic conditions"}),
    ("Search for gift ideas", {"query": "gift ideas for birthday"}),
    ("Find used cars for sale", {"query": "used cars for sale"}),
    ("Search best laptops 2024", {"query": "best laptops 2024"}),
    ("Look up flu symptoms", {"query": "flu symptoms"}),
    ("Find coffee shops near me", {"query": "coffee shops near me"}),
    ("Search how to make sourdough", {"query": "how to make sourdough bread"}),
    ("Look up currency exchange rates", {"query": "USD to EUR exchange rate"}),
    ("Search for hiking trails", {"query": "hiking trails near me"}),
    ("Find plumbers in my area", {"query": "plumbers near me"}),
    ("Search for DIY furniture projects", {"query": "DIY furniture projects"}),
    ("Look up concert tickets", {"query": "concert tickets near me"}),
    ("Find best pizza in town", {"query": "best pizza in town"}),
    ("Search for online courses", {"query": "online courses programming"}),
    ("Look up book recommendations", {"query": "best books 2024"}),
    ("Search for car insurance quotes", {"query": "car insurance quotes"}),
    ("Find gym memberships", {"query": "gym memberships near me"}),
    ("Search how to fix a flat tire", {"query": "how to fix a flat tire"}),
    ("Look up gardening tips", {"query": "gardening tips for beginners"}),
    ("Find dentists accepting patients", {"query": "dentists accepting new patients"}),
    ("Search for streaming services", {"query": "best streaming services"}),
    ("Look up train schedule", {"query": "train schedule"}),
    ("Search for moving companies", {"query": "moving companies near me"}),
    ("Find pet stores nearby", {"query": "pet stores near me"}),
    ("Search for wedding venues", {"query": "wedding venues near me"}),
    ("Look up tax deductions", {"query": "tax deductions 2024"}),
    ("Find tutors for math", {"query": "math tutors near me"}),
    ("Search for camping gear", {"query": "best camping gear"}),
    ("Look up pharmacy hours", {"query": "CVS pharmacy hours"}),
    ("Find electricians", {"query": "electricians near me"}),
    ("Search for baby names", {"query": "popular baby names 2024"}),
    ("Look up interview tips", {"query": "job interview tips"}),
    ("Search for language learning apps", {"query": "best language learning apps"}),
    ("Find dry cleaners nearby", {"query": "dry cleaners near me"}),
    ("Search for home improvement ideas", {"query": "home improvement ideas"}),
    ("Look up visa requirements", {"query": "visa requirements for Japan"}),
]

# ============ GET_SYSTEM_INFO (50 examples) ============
system_info_examples = [
    ("How much time is left on my timer?", {}),
    ("What's on my calendar today?", {}),
    ("Do I have any tasks?", {}),
    ("Are any lights on?", {}),
    ("What time is my alarm set for?", {}),
    ("What's the weather?", {}),
    ("Give me a summary of my day", {}),
    ("How many tasks do I have?", {}),
    ("Is the living room light on?", {}),
    ("What's left on my timer?", {}),
    ("Check my calendar for today", {}),
    ("What do I have scheduled?", {}),
    ("Any alarms set?", {}),
    ("What's the temperature?", {}),
    ("Show me my to-do list", {}),
    ("Which lights are on?", {}),
    ("How's the timer doing?", {}),
    ("What events are coming up?", {}),
    ("Tell me about today", {}),
    ("Any tasks pending?", {}),
    ("What's my schedule look like?", {}),
    ("Status of my timer", {}),
    ("Is it going to rain?", {}),
    ("What's the forecast?", {}),
    ("Do I have meetings today?", {}),
    ("How many minutes left on timer?", {}),
    ("What alarms do I have?", {}),
    ("Show my tasks", {}),
    ("Are there any lights off?", {}),
    ("What's happening today?", {}),
    ("Check the timer status", {}),
    ("Any calendar events?", {}),
    ("What's on my list?", {}),
    ("Status of bedroom light", {}),
    ("When is my next alarm?", {}),
    ("What's the weather forecast?", {}),
    ("How's my day looking?", {}),
    ("Pending tasks?", {}),
    ("Timer check", {}),
    ("What's the current temperature?", {}),
    ("My schedule for today", {}),
    ("Any reminders?", {}),
    ("Light status", {}),
    ("When does the timer go off?", {}),
    ("What's my agenda?", {}),
    ("Do I have anything tomorrow?", {}),
    ("Status of the house", {}),
    ("How's the weather outside?", {}),
    ("What tasks are pending?", {}),
    ("System status", {}),
]

# ============ THINKING (50 examples) ============
thinking_examples = [
    "Explain how neural networks learn",
    "Write a Python function to sort a list",
    "Solve this equation: 3x + 7 = 22",
    "Debug this code that has a memory leak",
    "Explain the theory of relativity",
    "Write a SQL query to find duplicates",
    "Calculate the compound interest on $10000",
    "Explain how blockchain works",
    "Write a recursive function for Fibonacci",
    "Analyze the pros and cons of remote work",
    "Explain quantum computing basics",
    "Write a regex to validate emails",
    "Calculate the probability of rolling doubles",
    "Explain the difference between TCP and UDP",
    "Write an algorithm for binary search",
    "Analyze this stock's performance",
    "Explain machine learning algorithms",
    "Write a function to detect palindromes",
    "Calculate the area of an irregular shape",
    "Explain how encryption works",
    "Write a class for a linked list",
    "Analyze this business problem",
    "Explain the immune system",
    "Write unit tests for this function",
    "Calculate the optimal route",
    "Explain cryptocurrency mining",
    "Write a parser for JSON",
    "Analyze this dataset",
    "Explain photosynthesis in detail",
    "Write an API endpoint",
    "Calculate mortgage payments",
    "Explain how vaccines work",
    "Write a sorting algorithm",
    "Analyze this legal contract",
    "Explain climate change science",
    "Write a web scraper",
    "Calculate return on investment",
    "Explain supply chain logistics",
    "Write a state machine",
    "Analyze this chemical reaction",
    "Explain how GPS works",
    "Write a cache implementation",
    "Calculate statistical significance",
    "Explain the electoral college",
    "Write a database schema",
    "Analyze this poem's meaning",
    "Explain how MRI machines work",
    "Write a compression algorithm",
    "Calculate depreciation",
    "Explain the scientific method",
]

# ============ NONTHINKING (50 examples) ============
nonthinking_examples = [
    "Hello",
    "Hi there",
    "Good morning",
    "How are you?",
    "What's the capital of France?",
    "Who wrote Harry Potter?",
    "What year did WWII end?",
    "What color is the sky?",
    "How many states in the USA?",
    "Who is the CEO of Tesla?",
    "What's 2 + 2?",
    "Thanks",
    "Thank you so much",
    "Goodbye",
    "See you later",
    "What day is it?",
    "Who invented the telephone?",
    "What's the largest ocean?",
    "How many continents are there?",
    "What language is spoken in Brazil?",
    "Hey",
    "What's up?",
    "Good evening",
    "Nice to meet you",
    "What's your name?",
    "Who painted the Mona Lisa?",
    "What's the speed of light?",
    "When is Christmas?",
    "What's the tallest mountain?",
    "Who discovered penicillin?",
    "You're welcome",
    "No problem",
    "Good night",
    "Have a nice day",
    "What time is it?",
    "Who is the president?",
    "What's the currency of Japan?",
    "How many days in a week?",
    "What's the chemical symbol for gold?",
    "Who wrote 1984?",
    "Greetings",
    "Howdy",
    "What's going on?",
    "I'm doing well",
    "Tell me a joke",
    "Define apple",
    "What's the opposite of hot?",
    "Name a planet",
    "What's the boiling point of water?",
    "Who is Mickey Mouse?",
]

# Generate all examples
all_examples = []

# Add control_light
for prompt, args in control_light_examples:
    all_examples.append(make_example(prompt, "control_light", args))

# Add set_timer
for prompt, args in set_timer_examples:
    all_examples.append(make_example(prompt, "set_timer", args))

# Add set_alarm
for prompt, args in set_alarm_examples:
    all_examples.append(make_example(prompt, "set_alarm", args))

# Add calendar
for prompt, args in calendar_examples:
    all_examples.append(make_example(prompt, "create_calendar_event", args))

# Add tasks
for prompt, args in task_examples:
    all_examples.append(make_example(prompt, "add_task", args))

# Add search
for prompt, args in search_examples:
    all_examples.append(make_example(prompt, "web_search", args))

# Add system_info
for prompt, args in system_info_examples:
    all_examples.append(make_example(prompt, "get_system_info", args))

# Add thinking
for prompt in thinking_examples:
    all_examples.append(make_example(prompt, "thinking", {"prompt": prompt}))

# Add nonthinking
for prompt in nonthinking_examples:
    all_examples.append(make_example(prompt, "nonthinking", {"prompt": prompt}))

# Shuffle
random.seed(42)
random.shuffle(all_examples)

# Write to file
with open("training_dataset_functions.jsonl", "w") as f:
    for ex in all_examples:
        f.write(json.dumps(ex) + "\n")

print(f"Generated {len(all_examples)} training examples")
print("Saved to training_dataset_functions.jsonl")
